# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'
  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "master" do |master|
 
    master.vm.box = "bento/ubuntu-18.04"
    master.vm.hostname = "master.example.com"
    master.vm.network "private_network", ip: "172.16.16.10"
	
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 6144
      v.cpus = 2
	  v.customize ["modifyvm", :id, "--audio", "none"]
	 end 
	  
    master.vm.provision "shell", path: "bootstrap_master.sh"
  end
  
  
  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do | node|
	 
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.16.1#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 6144
        v.cpus = 2
		v.customize ["modifyvm", :id, "--audio", "none"]
      end
      node.vm.provision "shell", path: "bootstrap_node.sh"
    end
  end
  end