# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "kmaster" do |kmaster|
    kmaster.vm.box = "bento/ubuntu-18.04"
    kmaster.vm.hostname = "kmaster.example.com"
    kmaster.vm.network "public_network", ip: "192.168.1.10"
	
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "kmaster"
      v.memory = 2048
      v.cpus = 2
	  v.customize ["modifyvm", :id, "--audio", "none"]
	 end 
	  
    kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh"
  end
  
  
  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "kworker1" do |workernode|
      workernode.vm.box = "bento/ubuntu-18.04"
      workernode.vm.hostname = "kworker#{i}.example.com"
      workernode.vm.network "public_network", ip: "192.168.1.1#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "kworker1"
        v.memory = 8192
        v.cpus = 2
		v.customize ["modifyvm", :id, "--audio", "none"]
      end
     # workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end
  end